apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: adminkamaldhari/chatapp:Production
          ports:
            - containerPort: 80
          resources:
            requests:
              #memory: "64Mi"
              cpu: "100m"
            limits:
              #memory: "128Mi"
              cpu: "200m"
